### ISSUE TITLE
SSH in command line is throwing an Exit Code 1 error.

### ISSUE THREAD

**Issue by petekofod** [petekofod/tstoolv2#4]
```
2020-11-04 11:21:08.484 DEBUG 11956 --- [nio-8082-exec-1] n.r.l.strolr.FederationsController       : Requesting backoffice statuses for AMTK
2020-11-04 11:21:08.551 DEBUG 11956 --- [nio-8082-exec-1] n.r.l.strolr.FederationsController       : Running remote script in Runtime as:  [ssh, -i, /hom
e/railwaynet/.ssh/tstool-dev, railwaynet@10.100.3.33, sudo, /usr/local/nagios/libexec/check_aim.tcl]
2020-11-04 11:21:09.205 ERROR 11956 --- [nio-8082-exec-1] n.r.l.strolr.FederationsController       : Can't execute the command line:
2020-11-04 11:21:09.205 ERROR 11956 --- [nio-8082-exec-1] n.r.l.strolr.FederationsController       : [ssh, -i, /home/railwaynet/.ssh/tstool-dev, railwayn
et@10.100.3.33, sudo, /usr/local/nagios/libexec/check_aim.tcl]
2020-11-04 11:21:09.218 ERROR 11956 --- [nio-8082-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in
 context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Invalid exit code of the command line: 
1] with root cause

java.lang.RuntimeException: Invalid exit code of the command line: 1
        at net.railwaynet.logdelivery.strolr.BackofficeController.getServerStatus(BackofficeController.java:86) ~[classes!/:0.0.1-SNAPSHOT]
        at net.railwaynet.logdelivery.strolr.BackofficeController.updateStatus(BackofficeController.java:122) ~[classes!/:0.0.1-SNAPSHOT]
        at net.railwaynet.logdelivery.strolr.BackofficeController.backoffice(BackofficeController.java:157) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_272]
```

**Comment by petekofod** [comment]
I will attempt to use the Jsch library instead.

**Comment by Lonebuddha** [comment]
Obsolete, replaced by JSch
